# Generated by Django 5.1 on 2024-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_hydjobs_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
