# Generated by Django 5.1 on 2024-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
